### ISSUE TITLE
AttributeError exception calling queue_unbind in stormed-amqp 0.2

### ISSUE THREAD

**Issue by sjlongland** [paolo-losi/stormed-amqp#20]
Hi,

I get the following message when I try to unbind a queue in stormed-amqp 0.2:
```
2015-01-09 07:08:47,594 root@9003[testremote.py: 338] ERROR Exception encountered evaluating e.rm_demand(['a2'])
Traceback (most recent call last):
  File "testremote.py", line 328, in prompt
    result = eval(cmd, globals(), local_vars)
  File "<string>", line 1, in <module>
  File "/home/stuartl/vrt/projects/rt/mmda_core/entity/remote.py", line 231, in rm_demand
    self._stat_ex, *['rt_cos.%s' % attr for attr in attributes]
  File "/home/stuartl/vrt/projects/rt/mmda_core/source/remote.py", line 208, in _unsubscribe_queue
    routing_key=t)
  File "/usr/lib64/python2.7/site-packages/stormed/channel.py", line 115, in queue_unbind
    self.send_method(_queue.Unind(ticket      = 0,
AttributeError: 'module' object has no attribute 'Unind'
```

The code for `_unsubscribe_queue` looks like this:
```

    def _unsubscribe_queue(self, exchange, *topics):
        '''
        Unsubscribe from one or more topics of an exchange.
        '''
        try:
            topic_set = self._subscriptions[exchange]
        except:
            # Not subscribed
            return

        if len(topics) == 0:
            # Unsubscribe from all topics
            topics = tuple(topic_set)

        for t in topics:
            topic_set.discard(t)
            if self._amqp_q is not None:
                self._log.debug('Unsubscribing receive queue (%s) to '\
                        'exchange %s topic %s',
                        self._amqp_q.queue, exchange, t)
                self._amqp_ch_rx.queue_unbind(
                        exchange=exchange,
                        queue=self._amqp_q.queue,
                        routing_key=t)
        if len(topic_set) == 0:
            del(self._subscriptions[exchange])
```

**Comment by sjlongland** [comment]
See https://github.com/paolo-losi/stormed-amqp/pull/21 for a fix to this issue.
